### ISSUE TITLE
[Dransik 2.0] Item Identification skill causes a crash on success

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#217]
You can learn the skill at 88,1509,0 by clicking the "Loop and Twigg" item on the floor and talking to the guy there. Default key to use the skill is i.  You will either get a failure message or a client crash.

**Comment by davidjreese** [comment]
Its not crashing for me in this build but I may not be identifying the right thing this is what happens when I click on things. I see the name plaque and then in the chat console this:
Select an object to inspect:
You do not recognize that object.

![Image](https://user-images.githubusercontent.com/669018/198733432-3d060f0f-06a8-4ae9-b122-9eadd5148994.png)

**Comment by AESeryth** [comment]
Try using it on items in your backpack. Often it takes several tries per success similar to other tradeskills at that level.

**Comment by davidjreese** [comment]
i can't get it to work. i clicked on everything dozens of times. is it working for you or do you have something it will fail on? not sure why if i am doing something wrong.

**Comment by AESeryth** [comment]
Sorry I think it only works on Equipment items.

**Comment by davidjreese** [comment]
found it, fixed it
