### ISSUE TITLE
[Dransik 2.0] Items that target the ground aren't working

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#218]
All of the monster spawning tools and the GM Tool give crosshairs to target the ground but don't work on the new client and will get you stuck unable to Use anything until a relog.  I'm not sure if any player items have similar targeting.

**Comment by davidjreese** [comment]
fixed this i believe. let me know if something else breaks - lol

**Comment by AESeryth** [comment]
The first use of the monster summoners works, but if I try to use another item with crosshairs the crosshairs show up then disappear right away and Use breaks.

Placing a wall or a guard is working now though.

**Comment by davidjreese** [comment]
Argh - i swear it worked multiple times for me. Wonder if I broke it fixing something else. Cursor logic is way too complicated

**Comment by davidjreese** [comment]
This worked for me using a lumberjack axe just fine

**Comment by hgesler** [comment]
It seems like if you select a target that the item can't be used on you get stuck in usecode. Not sure if this a script or code fix in some of these cases.

- Select raw spider legs, use on player, works as expected
- Select raw spider legs, use on ground, must relog.
- Select raw spider legs, use on itself or another item in backpack, must relog. This is easy to do since a single click is a use instead of a double click
=======
- Select well, use on any item in backpack, does nothing, but nothing breaks
- Select well, use on ground, must relog.
=======
- Select cooked spider legs or bat wings, use on player. Select cooked spider legs again; notice that the cursor changes to targeting >< box briefly before going back to a normal arrow select, then you must relog.

**Comment by hgesler** [comment]
With Lumberjack Axe

- Select lumberjack axe, select anything other than a tree you can chop (I tried a plant in a shop, the ground, a stump). It will return "You cannot chop there." Select axe again; it says "Where would you like to chop?" then the cursor change back to arrow almost immediately and you must relog.

**Comment by davidjreese** [comment]
Okay, I think I made progress on this. I am not sure all the permutations of things to try but I was able to try potions, spider legs, cooking, axes, chopping and other things.  i was also able to attack and equp/unequip.

I am sure its still messed up somewhere... please give it some reps

**Comment by hgesler** [comment]
I've found at least one issue so far, related to hotbars.

Drag the raw bat wings to your hotbar.
Click on raw bat wing in backpack, then use it on a lit oven. Works as expected.
Click on the bat wing IN THE HOTBAR, then use it on the lit oven. The cursor changes target mode briefly before reverting to arrow cursor, must relog.

**Comment by hgesler** [comment]
Another way to repro;
- Drag carpenters tools to hotbar
- Use carpenters tools on something in the world (I used on an oven, works on other objs). You'll get an error message about item being in possession, as expected.
- Click on carpenters tools in hotbar.

If clicking item in hotbar when first logging into game, it works fine. It's only after using the item from bp on an item in the world, then using from hotbar CLICK that it gets this way. Using F# keys does not break it.

**Comment by davidjreese** [comment]
fixed new way it broke
