### ISSUE TITLE
[Dransik 2.0] Minimap reveal button disappears when pressed when minimap is at the smallest/default size. 

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#340]
Loaded new client on account for first time, had default minimap size (small square size) and pressed the restore map reveal button. The button disappeared and nothing happened.

When I expanded size of minimap some it reappeared, then I was able to click it to restore my map reveal. Minor issue.

**Comment by davidjreese** [comment]
The button disappears when you press it because it is restoring the minimap. Are you sure it wasn't already in the restore process on the first press?

Also, the button wont show if you don't need a restore. So, after it completes it will disappear ( I am going to add some code to make it vanish when the process starts)

**Comment by davidjreese** [comment]
Updated this to be a bit more robust as described - won't show a button if the map reveal is in progress and I think I fixed the button flashing issue. It wasn't size related. Some logic that was always flawed and became more flawed when I made map reveal async.

Also, cleaned up some hardcoding of mapId to use flags for reveal state and lighting
