### ISSUE TITLE
[Engineering[ Add Global Chat

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#354]
Allow easier communication in game

**Comment by athacus** [comment]
I agree that this is a good feature mostly for the PVE server. When there is global chat on the PVP server, people will often flame each other. They will also spread alerts to everyone currently online when there are people hunting in certain places, or if there is criminals somewhere in the world. These are just friendly notes to keep in mind from what I've noticed since global chat used to exist and many in discord asked for it to be removed.

**Comment by davidjreese** [comment]
Thanks @athacus - i am going to enable it and we will see what happens. its so weird that its 'not a thing' in the game right now. I did separate it from system chat at least. i think adding ignore and other things will be needed though, to your point.

**Comment by athacus** [comment]
Okay sure. Could you add it as an additional chat option so there is still nearby chat like it is currently, then also global chat? This way you don't have to talk to everyone in the game if you just want to talk to someone in the same bank.
