### ISSUE TITLE
Unable to add a new Trade Skill in the Trade Object Editor

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#483]
![image](https://user-images.githubusercontent.com/74842329/210670868-56c5c498-e811-4e6b-b245-af83ab9b964d.png)
![image](https://user-images.githubusercontent.com/74842329/210670887-6edb3773-3ee8-42f0-bd5a-3f64de3e197c.png)

**Comment by davidjreese** [comment]
I added the Skills Editor back in and Enhanced Trade Data to let you add and remove Trade Skills. There are a max of 32 Trade Skills!

Use at your own risk. Deleting things or otherwise mucking with this stuff in the wrong way could have some effects between client, server and editor depending on whats hard coded and what is saved in with the character data, etc..

But now you can create new game skills and trade skills.
