### ISSUE TITLE
[Design] Backlog of Existing Quests -> Move to QuestLog system

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#693]
Made this ticket now that quest log is done

- [ ] etc
- [ ] etc
- [ ] etc
- [x] Kriastanna
- [x] Jo Harker
- [x] Anna Belle
- [x] Mufferaw

**Comment by hgesler** [comment]
Silvest Quests
- [x] Kristanna
- [x] Anna Bell
- [x] Jo Harker
- [x] Gerallo
- [x] Morgwang
- [x] Guard Murphy
- [x] Meegosh
- [x] William the Young
- [x] Mordred
- [x] Galen
- [ ] Silvest Seeker
- [x] Shubin
- [x] Sero
- [x] Mufferaw
- [x] JeanJeanie
- [x] Farmer GIles
- [x] Fustrin

**Comment by hgesler** [comment]
Mainland Quests

- [ ] Hulner
- [ ] Guild quest
- [ ] Clate
- [ ] Terry
- [ ] Andrea
- [ ] Molina
- [ ] Blanche
- [ ] Valette
- [ ] Gibson
- [ ] Water Castle

Trainer Quests
- [ ] Captain Chugga
- [ ] Raglnak
- [ ] Hungry Jack
- [ ] Yukoun
- [ ] Lady Arylem
- [ ] Klaresh
- [ ] Mirthik
- [ ] Tallen'im (needs quest redo and hook into id skill/book)
- [ ] Arabella

Velsinea
- [ ] Rigel
- [ ] Gratic
- [ ] Serpicio

**Comment by davidjreese** [comment]
Great list! I put this issue in the in progress state

**Comment by davidjreese** [comment]
NOTE: I am closing out the Milestone 2.1 so I moved this to Milestone 2.2 in progress.

**Comment by hgesler** [comment]
(-) Sero Quest: Display in quest log how many fish you've caught (ie. if 3 fish, 3/4) instead of just the amount needed for the quest
(-) Mufferaw Quest: When clicking on the NPC after completing quest, dialogue box comes up and immediately closes
(-) Shubin Quest: Same as Mufferaw
(-) Gerallo Quest: Typo, voilet -> violet, and the poem...is it missing line breaks?
(-) Meegosh Quest: Dialogue after quest completion is incorrect with the exit to island. Guard Murphy has the correct dialogue with the correct Silvest exit directions

**Comment by davidjreese** [comment]
all these are done
