### ISSUE TITLE
Global Chat request

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#794]
Bring global chat back, controversial but I think it's still more helpful than distrubtful

**Comment by ghost** [comment]
global becomes toxic, its nice but it was removed for a reason, can hope for the best i guess

**Comment by Galdelonian** [comment]
Global chat still exists. No need to add it in. I'd just modify the way the chat system works overall to make it easier to set up new chat channels.

Example: Adding a new window, typing in the name "event", going to your original chat window, clicking settings dropdown, selecting that event channel, and then clicking off of it and then tabbing to now see event in the original chat window is absurd. This is especially bad because nobody can figure it out on their own. You'd then need to close the new chat window. Players might not be sure if they can close those windows without severing that connection as the new window kind of feels like a connection.

**Comment by davidjreese** [comment]
done with global and help being part of UI now
