### ISSUE TITLE
Balance Feedback / List of Grievances - Post May Item Upgrade, Crafting, Alchemy Release

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#972]
- [x] mixing failure rate. "annoying is what is being said"
- [x] planting / digging failure rate at lev. "I have not explored crafting entirely yet I have only explored planting/harvesting/baking.  So far my feed back is simple. Fix this stupid waste of time system ASAP omfg who though increasing the fail rate was a good idea. I have 69 planting so why is it unreasonable to assume I should succeed at digging a whole more then 30/88 attempts. Planting a seed only worked about 10 or those 3. Harvesting only worked about half of those 10 @ level 60. I never mixed thank God. Because baking was a 20 percent success rate on bread @ level 50+ baking. Prior to the patch I would dig 100 percent of the time. Plant wheat 100 percent of the time harvest wheat 100 percent of the time and it still felt like to much but not have you outdone yourselves."
- [x] mining exp / smelting exp.  "mining experience at lvl 70+ is around 2-3k a swing, while smelting around the same level is 300-500 for a success. iron forging at lvl 50 gives 75 exp for  failure, and 189(with boost) for a success, no matter if you forge an item with  1 ingot (axe) or 35 (skull crusher). seems like a large balance issue, especially with the poor failure rates. the skill doesn't feel like it scales properly. Basically mining is 10x faster to lvl, and smithing feels just as equally slower. This is all with the weekend boost running"
- [ ] could we get a toggle for healing pots or some balancing around that? I'm so over spamming my hotkey 40 times a second -> auto-healing/consume potion until disabled is what he is asking for. too much hammering on key
- [ ] also consider removing the stutter on stam pots, keep the use time maybe so no other action except moving can happen during that timer
- [x]  MAYBE! Mining -> adjust crafting source materials down? Or otherwise balance?

**Comment by hgesler** [comment]
Going to test an adjust to mixing and planting/harvesting.

unsure if comment meant digging (mining) or digging (planting)

**Comment by davidjreese** [comment]
i think we got the skills handled - @hgesler you already fixed cooking and planting to be easier I think.

only thing left is some toggle to consume healing pots. not sure if that becomes its own issue or we just don't bother considering it

**Comment by PatrickKaHoTang** [comment]
Just my two cents on these.

> * [ ]  could we get a toggle for healing pots or some balancing around that? I'm so over spamming my hotkey 40 times a second -> auto-healing/consume potion until disabled is what he is asking for. too much hammering on key

I'm not a fan of changing the aspect of Dransik players can now auto-consume/healing a potion with a toggle. It can bring on laziness and could encourage macroing with hunting in low-mid level areas now that the upgrade system brought in the Inscriber (Ancient Knowledge Scrolls) and Infuser (Ancient Power) - I highly doubt higher level areas could make it work well.

> * [ ]  also consider removing the stutter on stam pots, keep the use time maybe so no other action except moving can happen during that timer

I am for reducing the stutter to around 0.8-1.0 seconds (make it comparable to a Greater Healing Potion stutter) and with your suggestion of making it so that no action other than moving can be performed until x amount of seconds have passed. Lets throw out a number and say 3 seconds.

I personally get stamina can be annoying, especially for mages, but there shouldn't be a total removal of a stutter just because it slows down gameplay or any action. There has to be some type of strategic use of stamina so it's not like someone can whack an NPC/player for hours on end. As much as I liked having no stamina before the mage/Tra'vaal update, it really needed to be implemented to balance out melee vs spell combat.

Perhaps an improvement for intelligence users only, let them gain stamina regeneration while in combat OR increase their stamina pool after 30/70/100 base intelligence as a small perk. Warriors don't need to use stamina potions as much as mages.

**Comment by davidjreese** [comment]
thanks for the feedback. these suggestions makes sense to me. may do something for higher than 100 stamina for mage as well as arcana points here in a future update

**Comment by davidjreese** [comment]
- [x] reduce stutter on sta potions to the 0.8-1s range

**Comment by davidjreese** [comment]
Reduces STA potion to .6 seconds and Greater STA potion to .8 second stutter
