### ISSUE TITLE
Console Format/Consistency Improvements

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#994]
- [x] echo (Channel) and print (channel) have different case for channel name
- [x] echo user channel and print user channel colors dont look closer enough to be associated
- [x] review all channel colors and use a solved pattern like AEs mapping for example

**Comment by PatrickKaHoTang** [comment]
- [ ] Allow font size to be changed with 3 options under Settings or under Configure - Small (75%), Medium (current - 100%), Large (125%), or whichever works better
- [ ] Allow players to remove "help" and "global" if leaving channel(s) from the list. Leave as default channels to join on new characters or returning players who never configured their UI
- [x] Make all channels print in lower case format. Example: Global, GLoBaL, GLOBAL = global
- [x] Add shortcuts to type in different chats instead of only tabbing to the correct chat
- Say - /s, /say
- Whisper - /w, /whisper
- Shout - /sh, /shout
- Guild - /gu, /guild
- Party - /p, /party

**Comment by davidjreese** [comment]
I am closing this @PatrickKaHoTang , font sizing should probably be it's own ticket if you want to add it.

Not sure I understand the help/global and if I do i dont agree with it. I think its an 'always option' but doesn't have to be used as is right now so not sure why they should ever be removed from the list as an option.

Give the new changes a test and make a ticket on font sizing if you like.

Thanks
